// DO NOT EDIT. This file is generated by Fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $_404 from "./routes/_404.tsx";
import * as $_app from "./routes/_app.tsx";
import * as $index from "./routes/index.tsx";
import * as $timer from "./routes/timer.tsx";
import * as $BackButton from "./islands/BackButton.tsx";
import * as $SetReps from "./islands/SetReps.tsx";
import * as $TimerControl from "./islands/TimerControl.tsx";
import type { Manifest } from "$fresh/server.ts";

const manifest = {
  routes: {
    "./routes/_404.tsx": $_404,
    "./routes/_app.tsx": $_app,
    "./routes/index.tsx": $index,
    "./routes/timer.tsx": $timer,
  },
  islands: {
    "./islands/BackButton.tsx": $BackButton,
    "./islands/SetReps.tsx": $SetReps,
    "./islands/TimerControl.tsx": $TimerControl,
  },
  baseUrl: import.meta.url,
} satisfies Manifest;

export default manifest;
